spring:
  datasource:
    url: jdbc:postgresql://dpg-d4ncoqshg0os73ckr2cg-a.oregon-postgres.render.com/java_project_99_db_sskq
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
