spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

sentry:
  dsn: ${SENTRY_AUTH_TOKEN:}
  environment: ${SPRING_PROFILES_ACTIVE:development}
